# Generated by Django 4.1.7 on 2023-09-26 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_fotogratia',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
