# Generated by Django 4.1.7 on 2023-09-26 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_publicada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='data_fotogratia',
            new_name='data_fotografia',
        ),
    ]
